info:
  description: testProyect
  version: 1.0

server:
  port: 8080
  context-path: /

management:
  context-path: /manage
  security:
    enabled: false
    roles: ACTUATOR
    

endpoints:
  enabled: true
  env:
    enabled: true
  restart:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false
  mappings:
    enabled: true

# MONGODB (MongoProperties)
spring:
  data:
    mongodb:
      uri: mongodb://scero:Dragon@mongodb/sampledb
      database: sampledb
