info:
  description: testProyect
  version: 1.0
  git:
    commitID: ${git.commit.id}
    commit:
      user:
        name: ${git.commit.user.name}

server:
  port: 8080
  context-path: /

management:
  context-path: /manage
  security:
    enabled: false
    roles: ACTUATOR
  info:
    git:
      enabled: true
      mode: simple
    
endpoints:
  enabled: true
  env:
    enabled: true
  restart:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false
  mappings:
    enabled: true

# MONGODB (MongoProperties)
#spring:
#  data:
#    mongodb:
#      uri: mongodb://scero:Dragon@mongodb/sampledb
#      database: sampledb

# Postgres
datasources:
  postgresql:
    jdbcUrl: jdbc:postgresql://postgresql:5432/sampledb
    driverClassName: org.postgresql.Driver
    username: scero
    password: Dragon
    poolName: AtlasHikariCP
    maxLifetime: 1200000
    maximumPoolSize: 10
    minimumIdle: 1
    schema: sampledb
    registerMbeans: true
