info:
  description: testProyect
  version: 1.0

# MONGODB (MongoProperties)
spring:
  data:
    mongodb:
      uri: mongodb://scero:Dragon@mongodb/sampledb
      database: sampledb

endpoints:
  enabled: true
  env:
    enabled: true
  restart:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false
  mappings:
    enabled: true
